name: CI
on: [push, pull_request]

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4
        with: 
          submodules: recursive
      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential
      - name: Test
        run: |
          make test
